// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	rbac2 "github.com/permission-dev/internal/api/grpc/rbac"
	"github.com/permission-dev/internal/ioc"
	"github.com/permission-dev/internal/repository"
	"github.com/permission-dev/internal/repository/dao"
	"github.com/permission-dev/internal/service/rbac"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	roleDAO := dao.NewRoleDao(db)
	roleRepository := repository.NewRoleRepository(roleDAO)
	resourceDao := dao.NewResourceDao(db)
	resourceRepository := repository.NewResourceRepository(resourceDao)
	permissionDAO := dao.NewPermissionDAO(db)
	permissionRepository := repository.NewPermissionRepository(permissionDAO)
	userRoleDAO := dao.NewUserDaoDAO(db)
	userRoleRepository := repository.NewUserRoleRepository(userRoleDAO)
	rolePermissionDAO := dao.NewRolePermissionDAO(db)
	rolePermissionRepository := repository.NewRolePermissionRepository(rolePermissionDAO)
	roleInclusionDAO := dao.NewRoleInclusionDAO(db)
	roleIncludeRepository := repository.NewRoleIncludeRepository(roleInclusionDAO)
	userPermissionDAO := dao.NewUserPermissionDAO(db)
	userPermissionRepository := repository.NewUserPermissionRepository(userPermissionDAO)
	businessConfigDAO := dao.NewBusinessConfigDAO(db)
	businessConfigRepository := repository.NewBusinessConfigRepository(businessConfigDAO)
	token := ioc.InitJwtToken()
	service := rbac.NewService(roleRepository, resourceRepository, permissionRepository, userRoleRepository, rolePermissionRepository, roleIncludeRepository, userPermissionRepository, businessConfigRepository, token)
	server := rbac2.NewServer(service)
	permissionService := rbac.NewPermissionService(userPermissionRepository)
	permissionServer := rbac2.NewPermissionServer(permissionService)
	v := ioc.InitGRPC(server, permissionServer, token)
	app := &ioc.App{
		GrpcServers: v,
	}
	return app
}

// wire.go:

var (
	baseSet = wire.NewSet(ioc.InitDB, ioc.InitJwtToken)
	rbacSet = wire.NewSet(dao.NewRoleDao, dao.NewResourceDao, dao.NewPermissionDAO, dao.NewUserDaoDAO, dao.NewRolePermissionDAO, dao.NewUserPermissionDAO, dao.NewRoleInclusionDAO, dao.NewBusinessConfigDAO, repository.NewRoleRepository, repository.NewResourceRepository, repository.NewPermissionRepository, repository.NewUserRoleRepository, repository.NewRolePermissionRepository, repository.NewUserPermissionRepository, repository.NewRoleIncludeRepository, repository.NewBusinessConfigRepository, rbac.NewService, rbac.NewPermissionService)
)
