mysql:
  dsn: "root:root@tcp(localhost:13316)/permission?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true"
server:
  governor:
    host: "0.0.0.0"
    port: 9003
  grpc:
    rbac:
      host: "0.0.0.0"
      port: 9002
trace:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
    serviceName: "permission-platform"
jwt:
  key: "permission_platform_key"
  issuer: "permission-platform"

kafka:
  addr: "localhost:9092"

userRoleBinlogEvent:
  topic: "user_roles_binlog"
  consumer:
    groupId: "user_roles_binlog_consumer_group"

userPermissionEvent:
  topic: "user-permission-events"

cache:
  local:
    capacity: 1000000
  multilevel:
    etcdKey: "hot_users"
    localCacheRefreshPeriod: 5000000000
    redisPingTimeout: 3000000000
    redisHealthCheckPeriod: 1000000000
    errorEvents:
      bitRingSize: 128
      rateThreshold: 0.8
      consecutiveCount: 3

redis:
  addr: "localhost:6379"